#cloud-config
package_update: true
package_upgrade: true
packages:
  - nano
  - curl
  - wget
  - qemu-guest-agent
  - ca-certificates
  - lsb-release
  - gnupg
  - net-tools
  - htop
  - python3
  - python3-apt
  - python3-distutils
  - python3-pip
  - python3-setuptools
  - python3-venv
  - sudo
  
users:
  - name: ${username}
    ssh_authorized_keys:
      - ${ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    shell: /bin/bash

disable_root: true
ssh_pwauth: false

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
